ads/urls.py
from django.urls import path
from . import views

app_name = 'ads'
urlpatterns = [
    path('', views.AdsListView.as_view(), name='ad_list'),
    path('ad/<int:pk>', views.AdsDetailView.as_view(), name='ad_detail'),
    path('create', views.AdsCreateView.as_view(), name='ad_create'),
    path('<int:pk>/update', views.AdsUpdateView.as_view(), name='ad_update'),
    path('<int:pk>/delete', views.AdsDeleteView.as_view(), name='ad_delete'),
    path('<int:pk>/picture', views.stream_file, name='ad_picture'),
    path('<int:pk>/comment/create', views.CommentCreateView.as_view(), name='ad_comment_create'),
    path('comment/<int:pk>/delete', views.CommentDeleteView.as_view(), name='ad_comment_delete'),
    path('<int:pk>/favorite', views.AddFavoriteView.as_view(), name='ad_favorite'),
    path('<int:pk>/unfavorite', views.DeleteFavoriteView.as_view(), name='ad_unfavorite'),
]

autos/urls.py
from django.urls import path
from . import views


app_name = 'autos'
urlpatterns = [
    path('', views.ListAuto.as_view(), name='auto-list'),
    path('main/create', views.CreateAuto.as_view(), name='auto-create'),
    path('main/<int:pk>/update', views.UpdateAuto.as_view(), name='auto-update'),
    path('main/<int:pk>/delete', views.DeleteAuto.as_view(), name='auto-delete'),
    path('lookup/', views.ListMake.as_view(), name='make-list'),
    path('lookup/create', views.CreateMake.as_view(), name='make-create'),
    path('lookup/<int:pk>/update', views.UpdateMake.as_view(), name='make-update'),
    path('lookup/<int:pk>/delete', views.DeleteMake.as_view(), name='make-delete'),
]

mysite/urls.py
import os
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls import url
from django.contrib.auth import views as auth_views
from django.views.static import serve
from django.views.generic import TemplateView

urlpatterns = [
    path('', include('home.urls')),  # Change to ads.urls
    path('admin/', admin.site.urls),  # Keep
    path('accounts/', include('django.contrib.auth.urls')),  # Keep
    url(r'^oauth/', include('social_django.urls', namespace='social')),  # Keep

    path('ads/', include('ads.urls')),
    path('autos', include('autos.urls')),
    path('cats/', include('cats.urls')),
]

# Serve the static HTML
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
urlpatterns += [
    url(r'^site/(?P<path>.*)$', serve,
        {'document_root': os.path.join(BASE_DIR, 'site'),
         'show_indexes': True},
        name='site_path'
        ),
]

# Serve the favicon - Keep for later
urlpatterns += [
    path('favicon.ico', serve, {
            'path': 'favicon.ico',
            'document_root': os.path.join(BASE_DIR, 'home/static'),
        }
    ),
]

# Switch to social login if it is configured - Keep for later
try:
    from . import github_settings
    social_login = 'registration/login_social.html'
    urlpatterns.insert(0,
                       path('accounts/login/', auth_views.LoginView.as_view(template_name=social_login))
                       )
    print('Using', social_login, 'as the login template')
except:
    print('Using registration/login.html as the login template')

# References

# https://docs.djangoproject.com/en/3.0/ref/urls/#include

autos/models.py
from django.db import models
from django.core.validators import MinLengthValidator


class Make(models.Model):
    name = models.CharField(max_length=40, help_text='Enter a make (e.g. Dodge)',
                            validators=[MinLengthValidator(
                                2, message='Make must be greater than 1 character')]
                            )

    def __str__(self):
        return self.name


class Auto(models.Model):
    nickname = models.CharField(max_length=200, validators=[
                                MinLengthValidator(2, "Nickname must be greater than 1 character")])
    mileage = models.PositiveIntegerField()
    comments = models.CharField(max_length=300)
    make = models.ForeignKey(Make, related_name='autos',
                             on_delete=models.CASCADE, null=False)

    def __str__(self):
        return self.nickname

autos/views.py
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.views.generic import ListView
from .models import Auto, Make
from django.contrib.auth.mixins import LoginRequiredMixin


class ListAuto(LoginRequiredMixin, ListView):
    model = Auto

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["make_count"] = Make.objects.all().count()
        return context


class CreateAuto(LoginRequiredMixin, CreateView):
    model = Auto
    fields = '__all__'
    success_url = reverse_lazy('autos:auto-list')


class UpdateAuto(LoginRequiredMixin, UpdateView):
    model = Auto
    fields = '__all__'
    success_url = reverse_lazy('autos:auto-list')


class DeleteAuto(LoginRequiredMixin, DeleteView):
    model = Auto
    fields = '__all__'
    success_url = reverse_lazy('autos:auto-list')


class ListMake(LoginRequiredMixin, ListView):
    model = Make
    template_name = 'autos/makes_list.html'


class CreateMake(LoginRequiredMixin, CreateView):
    model = Make
    fields = '__all__'
    success_url = reverse_lazy('autos:auto-list')


class UpdateMake(LoginRequiredMixin, UpdateView):
    model = Make
    fields = '__all__'
    success_url = reverse_lazy('autos:auto-list')


class DeleteMake(LoginRequiredMixin, DeleteView):
    model = Make
    fields = '__all__'
    success_url = reverse_lazy('autos:auto-list')

autos/templates/autos/auto_confirm_delete.html
{% extends 'base_bootstrap.html' %} {% block content %}
<form method="post">
  {% csrf_token %}
  <h1>Delete Auto</h1>

  <p>Are you sure you want to delete the auto: {{ auto }}?</p>
  {{ form }}

  <input type="submit" value="Yes, delete." />
</form>
{% endblock content %}

autos/templates/autos/auto_form.html
{% extends "base_bootstrap.html" %} {% block content %}
<form action="" method="post">
  {% csrf_token %}
  <table>
    {{ form.as_table }}
  </table>
  <input type="submit" value="Submit" />
  <input type="submit" onclick="window.location='{% url 'autos:auto-list' %}' ; return false;" value="Cancel" />
</form>
{% endblock %}

autos/templates/autos/auto_list.html
{% extends 'base_bootstrap.html' %}
{% block content %}
  <h1>Autos List</h1>
  {% if auto_list %}
  <ul>
    {% for auto in auto_list %}
      <li>{{auto|escape}} ({{auto.make|escape}}) (<a href='{% url 'autos:auto-update' auto.id %}'>Update</a> | <a href='{% url 'autos:auto-delete' auto.id %}'>Delete</a>)</li>
    {% endfor %}
  </ul>
  {% else %}
  <p>There are no autos in the library.</p>
  {% endif %}

  {% if make_count == 0 %}
    <p>Please add a make before you add an auto</p>
  {% else %}
    <p><a href='{% url 'autos:auto-create' %}'>Add an auto</a></p>
  {% endif %}

  <p>(<a href='{% url 'autos:make-list' %}'>View makes</a> ({{make_count}}) | <a href='{% url 'autos:make-create' %}'>Add a make</a>)</p>
{% endblock content %}

autos/templates/autos/make_confirm_delete.html
{% extends 'base_bootstrap.html' %} {% block content %}
<form method="post">
  {% csrf_token %}
  <h1>Delete Make</h1>

  <p>Are you sure you want to delete the make: {{ make }}?</p>
  {{ form }}

  <input type="submit" value="Yes, delete." />
</form>
{% endblock content %}

autos/templates/autos/make_form.html
{% extends 'base_bootstrap.html' %} {% block content %}
<form method="post">
  {% csrf_token %}
  <table>
    {{ form.as_table }}
  </table>
  <input type="submit" value="Submit" />
  <input type="submit" onclick="window.location='{% url 'autos:auto-list' %}'; return false;" value="Cancel" />
</form>
{% endblock content %}

autos/templates/autos/make_list.html
{% extends 'base_bootstrap.html' %} {% block content %}
<h1>Makes List</h1>

{% if make_list %}
<ul>
  {% for make in make_list %}
  <li>
    <p>
      {{ make }} (<a href="{% url 'autos:make-update' make.id %}">Update</a> |
      <a href="{% url 'autos:make-delete' make.id %}">Delete</a>)
    </p>
  </li>
  {% endfor %}
</ul>
{% else %}
<p>There are no makes in the library.</p>
{% endif %}
<p><a href="{% url 'autos:make-create' %}">Add a make</a></p>
<p><a href="{% url 'autos:auto-list' %}">Back to autos</a></p>
{% endblock content %}