ads/urls.py
from django.urls import path
from . import views

app_name = 'ads'
urlpatterns = [
    path('', views.AdsListView.as_view(), name='ad_list'),
    path('ad/<int:pk>', views.AdsDetailView.as_view(), name='ad_detail'),
    path('create', views.AdsCreateView.as_view(), name='ad_create'),
    path('<int:pk>/update', views.AdsUpdateView.as_view(), name='ad_update'),
    path('<int:pk>/delete', views.AdsDeleteView.as_view(), name='ad_delete'),
    path('<int:pk>/picture', views.stream_file, name='ad_picture'),
    path('<int:pk>/comment/create', views.CommentCreateView.as_view(), name='ad_comment_create'),
    path('comment/<int:pk>/delete', views.CommentDeleteView.as_view(), name='ad_comment_delete'),
    path('<int:pk>/favorite', views.AddFavoriteView.as_view(), name='ad_favorite'),
    path('<int:pk>/unfavorite', views.DeleteFavoriteView.as_view(), name='ad_unfavorite'),
]

cats/urls.py
from django.urls import path
from . import views

app_name = 'cats'
urlpatterns = [
    path('', views.CatListView.as_view(), name='list_cat'),
    path('main/create', views.CatCreateView.as_view(), name='create_cat'),
    path('main/<int:pk>/update', views.CatUpdateView.as_view(), name='update_cat'),
    path('main/<int:pk>/delete', views.CatDeleteView.as_view(), name='delete_cat'),
    path('lookup', views.BreedListView.as_view(), name='list_breed'),
    path('lookup/create', views.BreedCreateView.as_view(), name='create_breed'),
    path('lookup/<int:pk>/update', views.BreedUpdateView.as_view(), name='update_breed'),
    path('lookup/<int:pk>/delete', views.BreedDeleteView.as_view(), name='delete_breed'),
]

mysite/urls.py
import os
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls import url
from django.contrib.auth import views as auth_views
from django.views.static import serve
from django.views.generic import TemplateView

urlpatterns = [
    path('', include('home.urls')),  # Change to ads.urls
    path('admin/', admin.site.urls),  # Keep
    path('accounts/', include('django.contrib.auth.urls')),  # Keep
    url(r'^oauth/', include('social_django.urls', namespace='social')),  # Keep

    path('ads/', include('ads.urls')),
    path('autos', include('autos.urls')),
    path('cats/', include('cats.urls')),
]

# Serve the static HTML
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
urlpatterns += [
    url(r'^site/(?P<path>.*)$', serve,
        {'document_root': os.path.join(BASE_DIR, 'site'),
         'show_indexes': True},
        name='site_path'
        ),
]

# Serve the favicon - Keep for later
urlpatterns += [
    path('favicon.ico', serve, {
            'path': 'favicon.ico',
            'document_root': os.path.join(BASE_DIR, 'home/static'),
        }
    ),
]

# Switch to social login if it is configured - Keep for later
try:
    from . import github_settings
    social_login = 'registration/login_social.html'
    urlpatterns.insert(0,
                       path('accounts/login/', auth_views.LoginView.as_view(template_name=social_login))
                       )
    print('Using', social_login, 'as the login template')
except:
    print('Using registration/login.html as the login template')

# References

# https://docs.djangoproject.com/en/3.0/ref/urls/#include

cats/models.py
from django.db import models
from django.core import validators

class Breed(models.Model):
    name = models.CharField(max_length=40)

    def __str__(self):
        return self.name


class Cat(models.Model):
    nickname = models.CharField(max_length=50, validators=[validators.MinLengthValidator(2, 'Nickname must be greater than 1 character')])
    breed = models.ForeignKey('Breed', on_delete=models.CASCADE)
    foods = models.CharField(max_length=100)
    weight = models.PositiveSmallIntegerField()

    def __str__(self):
        return self.nickname

cats/views.py
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic import ListView, UpdateView, DeleteView, CreateView
from django.contrib.auth.mixins import LoginRequiredMixin
from .models import Cat, Breed

class CatListView(LoginRequiredMixin, ListView):
    model = Cat
    template_name = 'cats/cat_list.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["breed_count"] = Breed.objects.count()
        return context
    


class CatCreateView(LoginRequiredMixin, CreateView):
    model = Cat
    success_url = reverse_lazy('cats:list_cat')
    fields = '__all__'


class CatUpdateView(LoginRequiredMixin, UpdateView):
    model = Cat
    success_url = reverse_lazy('cats:list_cat')
    fields = '__all__'


class CatDeleteView(LoginRequiredMixin, DeleteView):
    model = Cat
    success_url = reverse_lazy('cats:list_cat')
    fields = '__all__'


class BreedListView(LoginRequiredMixin, ListView):
    model = Breed
    template_name = 'cats/breed_list.html'


class BreedCreateView(LoginRequiredMixin, CreateView):
    model = Breed
    success_url = reverse_lazy('cats:list_cat')
    fields = '__all__'


class BreedUpdateView(LoginRequiredMixin, UpdateView):
    model = Breed
    success_url = reverse_lazy('cats:list_cat')
    fields = '__all__'


class BreedDeleteView(LoginRequiredMixin, DeleteView):
    model = Breed
    success_url = reverse_lazy('cats:list_cat')
    fields = '__all__'

cats/templates/cats/breed_confirm_delete.html
{% extends 'base_bootstrap.html' %}

{% block content %}
    <h1>Delete Breed </h1>
    <p>Are you sure you want to delete the breed: {{breed}}?</p>
    <p></p>
    <form method="POST">{% csrf_token %}
        <input type="submit" value="Yes, delete.">
    </form>
{% endblock content %}

cats/templates/cats/breed_form.html
{% extends 'base_bootstrap.html' %}

{% block content %}
    <form method="post">{% csrf_token %}
        <table>
            {{form.as_table}}
        </table>
        <input type="submit" value="Submit">
        <input type="submit" value="Cancel" onclick="window.location='{% url 'cats:list_cat' %}'; return false;">
    </form>
{% endblock content %}

cats/templates/cats/breed_list.html
{% extends 'base_bootstrap.html' %}
{% block content %}
    <h1>Breeds List</h1>
    {% if breed_list%}
        <ul>
            {% for breed in breed_list %}
                <li>{{breed}} (<a href='{% url 'cats:update_breed' breed.id %}'>Update</a> | <a href='{% url 'cats:delete_breed' breed.id %}'>Delete</a>)</li>
            {% endfor %}
        </ul>
    {% else %}
        <p>There are no breeds in the library.</p>
    {% endif %}

    <p>    
        <a href="{% url 'cats:create_breed' %}">Add a breed</a>
    </p>

    <p>
        <a href="{% url 'cats:list_cat' %}">Back to cats</a>
    </p>
    
{% endblock content %}

cats/templates/cats/cat_confirm_delete.html
{% extends 'base_bootstrap.html' %}

{% block content %}
    <h1>Delete Cat </h1>
    <p>Are you sure you want to delete the cat: {{cat}}?</p>
    <p></p>
    <form method="POST">{% csrf_token %}
        <input type="submit" value="Yes, delete.">
    </form>
{% endblock content %}

cats/templates/cats/cat_form.html
{% extends 'base_bootstrap.html' %}

{% block content %}
    <form method="post">
        <table>{% csrf_token %}
            {{form.as_table}}
        </table>
        <input type="submit" value="Submit">
        <input tupe="submit" value="Cancel" onclick="window.location='{% url 'cats:list_cat' %}'; return false;">
    </form>
{% endblock content %}

cats/templates/cats/cat_list.html
{% extends 'base_bootstrap.html' %}
{% block content %}
    <h1>Cats List</h1>
    {% if cat_list%}
        <ul>
            {% for cat in cat_list %}
                <li>{{cat}} ({{cat.breed}}) (<a href='{% url 'cats:update_cat' cat.id %}'>Update</a> | <a href='{% url 'cats:delete_cat' cat.id %}'>Delete</a>)</li>
            {% endfor %}
        </ul>
    {% else %}
        <p>There are no cats in the library.</p>
    {% endif %}
    {% if breed_count %}
        <p>    
            <a href="{% url 'cats:create_cat' %}">Add a cat</a>
        </p>
    {% else %}
        <p>    
            Please add a breed before you add a cat. 
        </p>
    {% endif %}
      <p>
        <a href="{% url 'cats:list_breed' %}">View breeds</a> ({{breed_count}}) | 
          <a href="{% url 'cats:create_breed' %}">Add a breed</a>
        </p>
    
{% endblock content %}