ads/urls.py
from django.urls import path
from . import views

app_name = 'ads'
urlpatterns = [
    path('', views.AdsListView.as_view(), name='ad_list'),
    path('ad/<int:pk>', views.AdsDetailView.as_view(), name='ad_detail'),
    path('create', views.AdsCreateView.as_view(), name='ad_create'),
    path('<int:pk>/update', views.AdsUpdateView.as_view(), name='ad_update'),
    path('<int:pk>/delete', views.AdsDeleteView.as_view(), name='ad_delete'),
    path('<int:pk>/picture', views.stream_file, name='ad_picture'),
    path('<int:pk>/comment/create', views.CommentCreateView.as_view(), name='ad_comment_create'),
    path('comment/<int:pk>/delete', views.CommentDeleteView.as_view(), name='ad_comment_delete'),
    path('<int:pk>/favorite', views.AddFavoriteView.as_view(), name='ad_favorite'),
    path('<int:pk>/unfavorite', views.DeleteFavoriteView.as_view(), name='ad_unfavorite'),
]

mysite/urls.py
import os
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls import url
from django.contrib.auth import views as auth_views
from django.views.static import serve
from django.views.generic import TemplateView

urlpatterns = [
    path('', include('home.urls')),  # Change to ads.urls
    path('admin/', admin.site.urls),  # Keep
    path('accounts/', include('django.contrib.auth.urls')),  # Keep
    url(r'^oauth/', include('social_django.urls', namespace='social')),  # Keep

    path('ads/', include('ads.urls')),
    path('autos', include('autos.urls')),
    path('cats/', include('cats.urls')),
]

# Serve the static HTML
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
urlpatterns += [
    url(r'^site/(?P<path>.*)$', serve,
        {'document_root': os.path.join(BASE_DIR, 'site'),
         'show_indexes': True},
        name='site_path'
        ),
]

# Serve the favicon - Keep for later
urlpatterns += [
    path('favicon.ico', serve, {
            'path': 'favicon.ico',
            'document_root': os.path.join(BASE_DIR, 'home/static'),
        }
    ),
]

# Switch to social login if it is configured - Keep for later
try:
    from . import github_settings
    social_login = 'registration/login_social.html'
    urlpatterns.insert(0,
                       path('accounts/login/', auth_views.LoginView.as_view(template_name=social_login))
                       )
    print('Using', social_login, 'as the login template')
except:
    print('Using registration/login.html as the login template')

# References

# https://docs.djangoproject.com/en/3.0/ref/urls/#include

ads/models.py
from django.db import models
from django.core.validators import MinLengthValidator
from django.conf import settings
from taggit.managers import TaggableManager

class Ad(models.Model) :
    title = models.CharField(
            max_length=200,
            validators=[MinLengthValidator(2, "Title must be greater than 2 characters")]
    )
    price = models.DecimalField(max_digits=7, decimal_places=2, null=True)
    text = models.TextField()
    owner = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    picture = models.BinaryField(null=True, editable=True)
    content_type = models.CharField(max_length=256, null=True, help_text='The MIMEType of the file')
    comments = models.ManyToManyField(settings.AUTH_USER_MODEL, through='Comment', related_name='comments_owned')
    favorites = models.ManyToManyField(settings.AUTH_USER_MODEL, through='Favorite', related_name='favorite_ads')
    
    tags = TaggableManager()

    # Shows up in the admin list
    def __str__(self):
        return self.title


class Comment(models.Model):
    text = models.TextField(
        validators=[MinLengthValidator(3, "Comment must be greater than 3 characters")]
    )

    ad = models.ForeignKey(Ad, on_delete=models.CASCADE)
    owner = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    # Shows up in the admin list
    def __str__(self):
        if len(self.text) < 15 : return self.text
        return self.text[:11] + ' ...'
        

class Favorite(models.Model):
    ad = models.ForeignKey(Ad, on_delete=models.CASCADE)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)

    class Meta:
        unique_together = ('ad', 'user')

    def __str__(self):
        return f'{self.user.username} likes {self.ad.title[:10]}'

ads/forms.py
from django import forms
from .models import Ad
from django.core.files.uploadedfile import InMemoryUploadedFile
from .humanize import naturalsize


# Create the form class.
class CreateForm(forms.ModelForm):
    max_upload_limit = 2 * 1024 * 1024
    max_upload_limit_text = naturalsize(max_upload_limit)

    # Call this 'picture' so it gets copied from the form to the in-memory model
    # It will not be the "bytes", it will be the "InMemoryUploadedFile"
    # because we need to pull out things like content_type
    picture = forms.FileField(required=False, label='File to Upload <= '+max_upload_limit_text)
    upload_field_name = 'picture'

    # Hint: this will need to be changed for use in the ads application :)
    class Meta:
        model = Ad
        fields = ['title', 'price', 'text', 'picture', 'tags']  # Picture is manual

    # Validate the size of the picture
    def clean(self):
        cleaned_data = super().clean()
        pic = cleaned_data.get('picture')
        if pic is None:
            return
        if len(pic) > self.max_upload_limit:
            self.add_error('picture', "File must be < "+self.max_upload_limit_text+" bytes")
            
    # Convert uploaded File object to a picture
    def save(self, commit=True):
        instance = super(CreateForm, self).save(commit=False)

        # We only need to adjust picture if it is a freshly uploaded file
        f = instance.picture   # Make a copy
        if isinstance(f, InMemoryUploadedFile):  # Extract data from the form to the model
            bytearr = f.read()
            instance.content_type = f.content_type
            instance.picture = bytearr  # Overwrite with the actual image data

        if commit:
            instance.save()
            self.save_m2m()

        return instance


class CommentForm(forms.Form):
    comment = forms.CharField(required=True, max_length=500, min_length=3, strip=True)

# https://docs.djangoproject.com/en/3.0/topics/http/file-uploads/
# https://stackoverflow.com/questions/2472422/django-file-upload-size-limit
# https://stackoverflow.com/questions/32007311/how-to-change-data-in-django-modelform
# https://docs.djangoproject.com/en/3.0/ref/forms/validation/#cleaning-and-validating-fields-that-depend-on-each-other

ads/views.py
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import get_object_or_404, render, redirect
from django.urls import reverse_lazy
from ads.owner import OwnerCreateView, OwnerDeleteView, OwnerDetailView, OwnerListView, OwnerUpdateView
from .models import Ad, Comment, Favorite
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views import View
from .forms import CreateForm, CommentForm
from django.utils.decorators import method_decorator
from django.views.decorators.csrf import csrf_exempt
from django.db.models import Q

class AdsListView(OwnerListView):
    model = Ad
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        favorites = []
        if self.request.user.is_authenticated:
            favorites = self.request.user.favorite_ads.values_list('id', flat=True)
        context["favorites"] = favorites
        context["search"] = self.search
        return context
    
    def get_queryset(self):
        queryset = super().get_queryset()
        self.search = self.request.GET.get('search', False)
        if self.search:   
            queryset = queryset.filter(Q(title__contains=self.search) |
                                        Q(text__contains=self.search) |
                                        Q(tags__name__in=self.search.split(','))
                                        ).distinct()
        return queryset


class AdsDetailView(OwnerDetailView):
    model = Ad
    template_name = 'ads/ad_detail.html'
    def get(self, request, pk):
        ad = get_object_or_404(self.model.objects.prefetch_related('comment_set'), pk=pk)
        comments = ad.comment_set.all()
        form = CommentForm()
        context = {'ad': ad, 'comments': comments, 'comment_form': form}
        return render(request, self.template_name, context)


def stream_file(request, pk):
    ad = get_object_or_404(Ad, id=pk)
    response = HttpResponse()
    response['Content-Type'] = ad.content_type
    response['Content-Length'] = len(ad.picture)
    response.write(ad.picture)
    return response


class AdsCreateView(LoginRequiredMixin, View):
    template_name = 'ads/ad_form.html'
    success_url = reverse_lazy('ads:ad_list')
    def get(self, request):
        form = CreateForm()
        context = {'form': form}
        return render(request, self.template_name, context)

    def post(self, request):
        form = CreateForm(request.POST, request.FILES or None)
        if form.is_valid():
            ad = form.save(commit=False)
            ad.owner = request.user
            ad.save()
            form.save_m2m()
            return redirect(self.success_url)
        else:
            context = {'form': form}
            return render(request, self.template_name, context)


class AdsUpdateView(LoginRequiredMixin, View):
    template_name = 'ads/ad_form.html'
    success_url = reverse_lazy('ads:ad_list')
    def get(self, request, pk):
        ad = get_object_or_404(Ad.objects.filter(owner=request.user), pk=pk)
        form = CreateForm(instance=ad)
        context = {'form': form}
        return render(request, self.template_name, context)

    def post(self, request, pk):
        ad = get_object_or_404(Ad.objects.filter(owner=request.user), pk=pk)
        form = CreateForm(request.POST, request.FILES or None, instance=ad)
        if form.is_valid():
            form.save()
            return redirect(self.success_url)
        else:
            context = {'form': form}
            return render(request, self.template_name, context)


class AdsDeleteView(OwnerDeleteView):
    model = Ad
    success_url = reverse_lazy('ads:ad_list')


class CommentCreateView(LoginRequiredMixin, View):
    template_name = 'ads/ad_detail.html'
    def post(self, request, pk):
        ad = get_object_or_404(Ad.objects.prefetch_related('comment_set'), pk=pk)
        form = CommentForm(request.POST)
        if form.is_valid():
            comment = Comment(text=form.cleaned_data.get('comment'), ad=ad, owner=request.user)
            comment.save()
            return redirect(reverse_lazy('ads:ad_detail', args=[pk]))
        else:
            context = {'ad': ad, 'form': form, 'comments': ad.comment_set}
            return render(request, self.template_name, context)


class CommentDeleteView(OwnerDeleteView):
    model = Comment

    # https://stackoverflow.com/questions/26290415/deleteview-with-a-dynamic-success-url-dependent-on-id
    def get_success_url(self):
        ad = self.object.ad
        return reverse_lazy('ads:ad_detail', args=[ad.id])

@method_decorator(csrf_exempt, name='dispatch')
class AddFavoriteView(LoginRequiredMixin, View):
    def post(self, request, pk):
        ad = get_object_or_404(Ad, pk=pk)
        favorite, created = Favorite.objects.get_or_create(ad=ad, user=request.user)
        return HttpResponse()

@method_decorator(csrf_exempt, name='dispatch')
class DeleteFavoriteView(LoginRequiredMixin, View):
    def post(self, request, pk):
        ad = get_object_or_404(Ad, pk=pk)
        Favorite.objects.filter(ad=ad, user=request.user).delete()
        return HttpResponse()

ads/templates/ads/ad_confirm_delete.html
{% extends "base_menu.html" %}
{% block content %}
<h1>Delete Ad</h1>

<p>Are you sure you want to delete the ad: {{ ad }}?</p>

<form action="" method="POST">
  {% csrf_token %}
  <input type="submit" value="Yes, delete.">
</form>
{% endblock %}

ads/templates/ads/ad_detail.html
{% extends "base_menu.html" %}
{% load humanize %} <!-- https://docs.djangoproject.com/en/3.0/ref/contrib/humanize -->
{% block head %}
<style>
.overlay{
  position: fixed;
  top: 0;
  left: 0;
  width: 100%;
  height: 100%;
  z-index: 10;
  display: none;
  background-color: rgba(0,0,0,0.5); /*dim the background*/
}
</style>
{% endblock %}
{% block content %}
{% if ad.content_type %}
<div id="overlay" class="overlay" style="text-align: center;"
   onclick="document.getElementById('overlay').style.display = 'none';" >
<img style="width:90%;margin-top: 50px; border:3px solid black;" src="{% url 'ads:ad_picture' ad.id %}">
</div>
{% endif %}
<span style="float: right;">
({{ ad.updated_at|naturaltime }})
{% if ad.owner == user %}
<a href="{% url 'ads:ad_update' ad.id %}"><i class="fa fa-pencil"></i></a>
<a href="{% url 'ads:ad_delete' ad.id %}"><i class="fa fa-trash"></i></a>
{% endif %}
</span>
<h1>{{ ad.title }}</h1>
{% if ad.content_type %}
<img style="float:right; max-width:50%;" src="{% url 'ads:ad_picture' ad.id %}"
    onclick="document.getElementById('overlay').style.display = 'block';">
{% endif %}
<p>
{{ ad.text }}
</p>
<p>
  Tags: {% for tag in ad.tags.all %}<span style="border:1px grey solid; background-color: LightGreen;">{{tag.name}}</span> {% endfor %}
</p>
<p>
Price: ${{ ad.price }}
</p>
{% if user.is_authenticated %}
<br clear="all"/>
<p>
{% load crispy_forms_tags %}
<form method="post" action="{% url 'ads:ad_comment_create' ad.id %}">
    {% csrf_token %}
    {{ comment_form|crispy }}
<input type="submit" value="Submit">
</form>
</p>
{% endif %}
{% for comment in comments %}
<p> {{ comment.text }} 
({{ comment.updated_at|naturaltime }})
{% if user == comment.owner %}
<a href="{% url 'ads:ad_comment_delete' comment.id %}"><i class="fa fa-trash"></i></a>
{% endif %}
</p>
{% endfor %}
{% endblock %}

ads/templates/ads/ad_form.html
{% extends "base_menu.html" %}
{% load crispy_forms_tags %}
{% block content %}
<p>
  <form action="" method="post" id="upload_form" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form|crispy }}
    <input type="submit" value="Submit">
    <input type="submit" value="Cancel" onclick="window.location.href='{% url 'ads:ad_list' %}';return false;">
  </form>
</p>
<script>
  $("#upload_form").submit(function() {
    console.log('Checking file size');
    if (window.File && window.FileReader && window.FileList && window.Blob) {
        var file = $('#id_{{ form.upload_field_name }}')[0].files[0];
        if (file && file.size > {{ form.max_upload_limit }} ) {
            alert("File " + file.name + " of type " + file.type + " must be < {{ form.max_upload_limit_text }}");
        return false;
      }
    }
  });
</script>
{% endblock %}

ads/templates/ads/ad_list.html
{% extends "base_menu.html" %}
{% load humanize %}
{% block content %}
<h1>Ads</h1>
<p>
{% if ad_list %}
<div style="float:right">
  <form>
    <input type="text" placeholder="Search.." name="search" {% if  search  %}value="{{ search }}"{% endif %}>
    <button type="submit"><i class="fa fa-search"></i></button>
    <a href="{% url 'ads:ad_list' %}"><i class="fa fa-undo"></i></a>
  </form>
</div>
<ul>
  {% for ad in ad_list %}
    <li>
        <a href="{% url 'ads:ad_detail'  ad.id %}">{{ ad.title }}</a>
        {% if ad.owner == user %}
        (<a href="{% url 'ads:ad_update' ad.id %}">Edit</a> |
        <a href="{% url 'ads:ad_delete' ad.id %}">Delete</a>)
        {% endif %}
        {% if user.is_authenticated %}
        <!-- Two hrefs with two stacked icons each - one showing and one hidden -->
        <a href="#" onclick=
            "favPost('{% url 'ads:ad_unfavorite' ad.id %}', {{ ad.id }} );return false;"
            {% if ad.id not in favorites %} style="display: none;" {% endif %}
            id="favorite_star_{{ad.id}}">
        <span class="fa-stack" style="vertical-align: middle;">
        <i class="fa fa-star fa-stack-1x" style="color: orange;"></i>
        <i class="fa fa-star-o fa-stack-1x"></i>
        </span>
        </a>
        <!-- the second href -->
        <a href="#" onclick=
             "favPost('{% url 'ads:ad_favorite' ad.id %}', {{ ad.id }} );return false;"
            {% if ad.id in favorites %} style="display: none;" {% endif %}
            id="unfavorite_star_{{ad.id}}">
        <span class="fa-stack" style="vertical-align: middle;">
        <i class="fa fa-star fa-stack-1x" style="display: none; color: orange;"></i>
        <i class="fa fa-star-o fa-stack-1x"></i>
        </span>
        </a>
        {% endif %}
        <br>
        <div style="left:10 px">{{ ad.text|truncatechars:50 }}</div>
        <small> posted by {{ ad.owner }} {{ad.created_at|naturaltime}}</small>
    </li>
  {% endfor %}
</ul>
{% else %}
  <p>There are no ads in the database.</p>
{% endif %}
</p>
<p>
<a href="{% url 'ads:ad_create' %}">Add an ad</a> |
{% if user.is_authenticated %}
<a href="{% url 'logout' %}?next={% url 'ads:ad_list' %}">Logout</a>
{% else %}
<a href="{% url 'login' %}?next={% url 'ads:ad_list' %}">Login</a>
{% endif %}
</p>
<script>
  function getCookie(name) {
    let cookieValue = null;
    if (document.cookie && document.cookie !== '') {
        const cookies = document.cookie.split(';');
        for (let i = 0; i < cookies.length; i++) {
            const cookie = cookies[i].trim();
            // Does this cookie string begin with the name we want?
            if (cookie.substring(0, name.length + 1) === (name + '=')) {
                cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                break;
            }
        }
    }
    return cookieValue;
}
const csrftoken = getCookie('csrftoken');
  $.ajaxSetup({
    headers: {
        'Content-Type': 'application/json',
        'Accept': 'application/json',
        'X-CSRFToken': getCookie("csrftoken")
    }
  });
  function favPost(url, ad_id) {
    $.post(url, {}, function(){
      $('#favorite_star_' + ad_id).toggle()
      $('#unfavorite_star_' + ad_id).toggle()
    }).fail(function(xhr) {
      alert('Url failed with '+xhr.status+' '+url);
  });
  }
</script>
{% endblock %}

ads/templates/ads/comment_confirm_delete.html
{% extends "base_bootstrap.html" %}
{% block content %}
<h1>Delete Comment</h1>

<p>Are you sure you want to delete</p>
<p>{{ comment.text }}?</p>

<form action="" method="POST">
  {% csrf_token %}
  <input type="submit"  class="btn btn-primary" value="Yes, delete.">
  <a href="{% url 'ads:ad_detail' comment.ad.id %}" class="btn btn-secondary">Cancel</a>
</form>
{% endblock %}